//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*

 */
// Code generated by main. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ACMEDNSChallenge) DeepCopyInto(out *ACMEDNSChallenge) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ACMEDNSChallenge.
func (in *ACMEDNSChallenge) DeepCopy() *ACMEDNSChallenge {
	if in == nil {
		return nil
	}
	out := new(ACMEDNSChallenge)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ACMEDNSChallenge) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ACMEDNSChallengeList) DeepCopyInto(out *ACMEDNSChallengeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ACMEDNSChallenge, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ACMEDNSChallengeList.
func (in *ACMEDNSChallengeList) DeepCopy() *ACMEDNSChallengeList {
	if in == nil {
		return nil
	}
	out := new(ACMEDNSChallengeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ACMEDNSChallengeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ACMEDNSChallengeSpec) DeepCopyInto(out *ACMEDNSChallengeSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ACMEDNSChallengeSpec.
func (in *ACMEDNSChallengeSpec) DeepCopy() *ACMEDNSChallengeSpec {
	if in == nil {
		return nil
	}
	out := new(ACMEDNSChallengeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ACMEDNSChallengeStatus) DeepCopyInto(out *ACMEDNSChallengeStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ACMEDNSChallengeStatus.
func (in *ACMEDNSChallengeStatus) DeepCopy() *ACMEDNSChallengeStatus {
	if in == nil {
		return nil
	}
	out := new(ACMEDNSChallengeStatus)
	in.DeepCopyInto(out)
	return out
}
