/*

 */
// Code generated by main. DO NOT EDIT.

// +k8s:deepcopy-gen=package
// +groupName=resource.cert-manager.activated.io
package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// ACMEDNSChallengeList is a list of ACMEDNSChallenge resources
type ACMEDNSChallengeList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata"`

	Items []ACMEDNSChallenge `json:"items"`
}

func NewACMEDNSChallenge(namespace, name string, obj ACMEDNSChallenge) *ACMEDNSChallenge {
	obj.APIVersion, obj.Kind = SchemeGroupVersion.WithKind("ACMEDNSChallenge").ToAPIVersionAndKind()
	obj.Name = name
	obj.Namespace = namespace
	return &obj
}
