
imagePullSecrets: []

groupName: certmanager.bluebird.acresecurity.com

certManager:
  namespace: cert-manager
  serviceAccountName: cert-manager

image:
  repository: ghcr.io/activatedio/certmanager-webhook-resource
  tag: v0.0.0
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 443

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
