---
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.resource.cert-manager.activated.io
  labels:
    app: {{ include "certmanager-webhook-resource.name" . }}
    chart: {{ include "certmanager-webhook-resource.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    cert-manager.io/inject-ca-from: "{{ .Release.Namespace }}/{{ include "certmanager-webhook-resource.servingCertificate" . }}"
spec:
  group: resource.cert-manager.activated.io
  groupPriorityMinimum: 1000
  versionPriority: 15
  service:
    name: {{ include "certmanager-webhook-resource.fullname" . }}
    namespace: {{ .Release.Namespace }}
  version: v1alpha1
