apiVersion: v1
kind: Service
metadata:
  name: {{ include "certmanager-webhook-resource.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ include "certmanager-webhook-resource.name" . }}
    chart: {{ include "certmanager-webhook-resource.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    app: {{ include "certmanager-webhook-resource.name" . }}
    release: {{ .Release.Name }}
